version: '3'

services:
  rustapi:
    container_name: rustapi
    image: ksi05298/rustapi:1.0.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@rustapi-db:5432/postgres
    ports:
      - '8080:8080'
    depends_on:
      - rustapi-db
  rustapi-db:
    container_name: rustapi-db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}